

CREATE TABLE public."time" (
	time_selection_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	start_date date NULL,
	end_date date NULL,
	CONSTRAINT time_pk PRIMARY KEY (time_selection_id)
);



CREATE TABLE public.course (
	course_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	course_name varchar NULL,
	time_selection_id int4 NULL,
	CONSTRAINT course_pk PRIMARY KEY (course_id)
);

ALTER TABLE public.course ADD CONSTRAINT course_fk FOREIGN KEY (time_selection_id) REFERENCES "time"(time_selection_id) ON UPDATE CASCADE ON DELETE SET NULL;



